name: Rust

on:
  [ push ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3
      - name: Setup | Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt, clippy
      - name: Setup | Std
        run: rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
      - name: Setup | Default to nightly
        run: rustup default nightly
      - name: Setup | ldproxy
        run: cargo install ldproxy
      - name: Build
        run: cargo build --release --verbose
      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: build-results
          path: ./target/riscv32imc-esp-espidf/release/*
